### PR TITLE
Change authentication configuration

### PR DESCRIPTION
**Pull request by kvnrynfl**
## Changes

- Enable fortify email verification
- Enable terms and privacy policy
- Enable profile photo

## Checklist

- [x] Have performed local testing
- [x] Have formatted correctly
- [x] Have followed the contribution guidelines
- [ ] This PR includes only documentation changes, no code change.

### CODE REVIEW

**Review by kimlanisa — APPROVED** [review]

**Review by kimlanisa — APPROVED** [review]

**Comment by lanisriagustin** [comment]
LGTM

**Review by kimlanisa — APPROVED** [review]
DONE

**Review by kimlanisa — APPROVED** [review]
LGTM

**Review by kimlanisa — COMMENTED** [review]
LGTM

**Review by kimlanisa — APPROVED** [review]
LGTM

**Review by kimlanisa — APPROVED** [review]
LGTM

**Review by kimlanisa — APPROVED** [review]
LGTM

**Pull request merged**
